version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - products
      - recommendation
      - products-db
    networks:
      - app-network

  products:
    build:
      context: ./product
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - products-db
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network

  products-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:8.0.0-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  recommendation:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
  
  otel-collector:
    build:
      context: ./otel-collector
      dockerfile: Dockerfile
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    depends_on:
      - jaeger
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14250:14250"
      - "4317"
      - "4318"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
