version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - products
      - recommendation
    networks:
      - app-network

  products:
    build:
      context: ./combined-fastapi
      dockerfile: Dockerfile
    depends_on:
      - products-db
    ports:
      - "8000:8000"
    networks:
      - app-network

  products-db:
    image: postgres:17-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network

  recommendation:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
