version: '3.8'

services:
  frontend:
    image: ghcr.io/akhilmanoj03/frontend:test
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - authentication
      - products
      - recommendation
    networks:
      - app-network
  
  authentication:
    image: ghcr.io/akhilmanoj03/authentication:test
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - products-db
    networks:
      - app-network

  products:
    image: ghcr.io/akhilmanoj03/product:test
    env_file:
      - .env
    depends_on:
      - authentication
      - products-db
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network

  products-db:
    build:
      context: ../database
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:8.0.0-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  recommendation:
    image: ghcr.io/akhilmanoj03/recommendation:test
    depends_on:
      - products-db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
