networks:
  craftista:
    driver: bridge

services:
  products-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - products-db
      - redis
      - otel-collector
    env_file:
      - .env
    networks:
      - craftista
    ports:
      - "8000:8000"

  products-db:
    image: postgres:17-alpine3.21
    env_file:
      - .env
    networks:
      - craftista
    ports:
      - "5432:5432"
    
  redis:
    image: redis:8.0.0-alpine
    networks:
      - craftista
    ports:
      - "6379:6379"

  otel-collector:
    build: ../otel-collector
    networks:
      - craftista
    ports:
      - "4317:4317"
      - "4318:4318"
  
  jaeger:
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - craftista
    ports:
      - "16686:16686"
      - "14250:14250"
      - "4317"
      - "4318"
